### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by clippers1** [binarycraft007/wechat-hook#1]

**Comment by binarycraft007** [comment]
> _No description provided._

1. download the release build [v0.0.1](https://github.com/binarycraft007/wechat-hook/releases/download/v0.0.1/wechat-injector.exe)
2. download [wechat v3.9.5.81](https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.5.81/WeChatSetup-3.9.5.81.exe)
3. install wechat v3.9.5.81.
4. run wechat-injector.exe with administrator permission.
5. curl the healthcheck api to see if it works: curl http://127.0.0.1:8080/api/healthcheck
